print("=" * 40)
print("   WELCOME TO DEVELOPER OS")
print("Current Version: v 0.1.0")
print("=" * 40)
name = input("Enter Name: ")
location = input("Your location: ")
current_program = input("What program are you cuurently learning? ")
dream_career = input("What is your dream profession? ")
github = input("What is your Github username? ")
favourite_club = input("What is your Favourite football club? ")
# Welcome Page
print("=" * 40)
print("      PROFILE")
print(f"Welcome, {name} !")
print("=" * 40)
print(f"Name: {name}")
print(f"Location: {location}")
print(f"Current Program: {current_program}")
print(f"Dream Career: {dream_career}")
print(f"Github: {github}")
print(f"Favourite Club: {favourite_club}")
# Utilities Section
print("=" * 40)
print("  LOADING UTILITIES.....")
print("=" * 40)
# Calculator
print("=" * 40)
print("  SIMPLE CALCULATOR")
print("=" * 40)
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print(f"Sum: {a + b}")
print(f"Difference: {a - b}")
print(f"Product: {a * b}")
print(f"Quotient: {a / b}")
print(f"Remainder: {a % b}")
print(f"Power: {a ** b}")
# Goodbye section
print("=" * 40)
print("Thank you for using DeveloperOS!")
print("Version: v0.1.0")
print("=" * 40)
